language: cpp

sudo: false

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.5
    packages:
     - clang-3.5

matrix:
  include:
     # Coverage
     - os: osx
       compiler: clang
       env: NODE_VERSION="0.10.38" COVERAGE=true FLAGS="--debug"
     # Debug + Clang sanitizers
     - os: linux
       compiler: clang
       env: NODE_VERSION="0.10.38" SANITIZE=address
     - os: linux
       compiler: clang
       env: NODE_VERSION="0.10.38" SANITIZE=integer
     # Linux
     - os: linux
       compiler: clang
       env: NODE_VERSION="0.12.2" PUBLISH=true # node abi 14
     - os: linux
       compiler: clang
       env: NODE_VERSION="0.10.38" PUBLISH=true # node abi 11
     # OS X
     - os: osx
       compiler: clang
       env: NODE_VERSION="0.12.2" PUBLISH=true # node abi 14
     - os: osx
       compiler: clang
       env: NODE_VERSION="0.10.38" PUBLISH=true # node abi 11

env:
  global:
   - JOBS: "8"
   - secure: bLTdbWwf3v8X7yJlLLqPc9BRhFquwma4oYL9T2C38FXzSuqhXJZF+kNXjHd85E4lJNnuLXDjrPJLLkigd70J9Tclu2XQvy3cGzXI+EMsO6rDvQN24Eoi6uJ/qHhTrAoud526ouxO8qk9YYLjD6UWX1EOtqcEdwPMose8L1wsMZI=
   - secure: lmfuNtK0/ubV4ZZobgfeKY6DzG41ZciS4a00yCe29jHLxAg+EEmB/qpsW5d1//cC94OKsAySW08xp2uX5wBVvtryaaoiwU7fdKF9DOxHRHieGw/3+m8NNjELkd5hKMKiqDj7l4QPMchzBQR2PQkoG0UMCGUFe+RmzZ2/iCdGHXU=

before_install:
 - export COVERAGE=${COVERAGE:-false}
 - export SANITIZE=${SANITIZE:-false}
 - if [[ $(uname -s) == 'Linux' ]]; then
     export CXX="clang++-3.5";
     export CC="clang-3.5";
     export PYTHONPATH=$(pwd)/mason_packages/.link/lib/python2.7/site-packages;
   else
     export PYTHONPATH=$(pwd)/mason_packages/.link/lib/python/site-packages;
   fi;
 - source ./test/install_node.sh ${NODE_VERSION}
 - export PATH=./node_modules/.bin/:$PATH
 - git clone --depth 1 https://github.com/mapbox/mason.git ./.mason
 - export MASON_DIR=$(pwd)/.mason
 - export PATH=$(pwd)/.mason:$(pwd)/mason_packages/.link/bin:$PATH
 - ./.mason/mason install protobuf 2.6.1
 - ./.mason/mason link protobuf 2.6.1
 - export PKG_CONFIG_PATH=$(pwd)/mason_packages/.link/lib/pkgconfig/
 - export CXXFLAGS="-I$(pwd)/mason_packages/.link/include"
 - export LDFLAGS="-L$(pwd)/mason_packages/.link/lib"

install:
 - if [[ ${COVERAGE} == true ]]; then
     PYTHONUSERBASE=$(pwd)/mason_packages/.link pip install --user cpp-coveralls;
     export CXXFLAGS="--coverage ${CXXFLAGS}";
     export LDFLAGS="--coverage ${LDFLAGS}";
   fi
 - if [[ ${SANITIZE} != false ]]; then
     export CXXFLAGS="-fsanitize=${SANITIZE} ${CXXFLAGS}";
     export LDFLAGS="-fsanitize=${SANITIZE} ${LDFLAGS}";
   fi
 - npm install --build-from-source --clang=1 ${FLAGS}

script:
- npm test

after_success:
- if [[ ${COVERAGE} == true ]]; then cpp-coveralls --exclude node_modules --exclude tests --build-root build --gcov-options '\-lp' --exclude ./mason_packages --exclude src/pbf.hpp --exclude ./deps --exclude build/Release/obj/gen --exclude src/binding.hpp > /dev/null; fi;
- if [[ ${PUBLISH} == true ]]; then ./test/travis-publish.sh; fi;
